/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["toggle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["hide"];
        delete: operations["unhide"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateEventRequest: {
            /** @enum {string} */
            type: "lost_found" | "activity" | "club" | "help" | "giveaway" | "happening" | "notice";
            title: string;
            body: string;
            location: components["schemas"]["LatLng"];
            applyable: boolean;
            /** Format: date-time */
            expiresAt: string;
            tags: string[];
        };
        LatLng: {
            /** Format: double */
            lng: number;
            /** Format: double */
            lat: number;
        };
        AuthorCard: {
            displayName: string;
            avatarSeed: string;
            /** Format: date-time */
            memberSince: string;
        };
        EventDetail: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "lost_found" | "activity" | "club" | "help" | "giveaway" | "happening" | "notice";
            /** @enum {string} */
            status: "active" | "resolved" | "expired" | "removed" | "under_review";
            title: string;
            body: string;
            location: components["schemas"]["LatLng"];
            applyable: boolean;
            /** Format: int32 */
            score: number;
            /** Format: int32 */
            applicationCount: number;
            tags: components["schemas"]["TagRef"][];
            author: components["schemas"]["AuthorCard"];
            viewerState: components["schemas"]["ViewerState"];
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            resolvedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TagRef: {
            name: string;
            slug: string;
        };
        ViewerState: {
            voted: boolean;
            hidden: boolean;
            applied: boolean;
            isAuthor: boolean;
        };
        VoteResponse: {
            /** Format: int32 */
            score: number;
            voted: boolean;
        };
        ReportRequest: {
            /** @enum {string} */
            reason: "spam" | "offensive" | "scam" | "danger" | "other";
            detail?: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
            displayName: string;
            /** @enum {string} */
            transport?: "cookie" | "bearer";
        };
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
            token?: string;
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            displayName: string;
            avatarSeed: string;
            /** Format: date-time */
            createdAt: string;
        };
        LoginRequest: {
            email: string;
            password: string;
            /** @enum {string} */
            transport?: "cookie" | "bearer";
        };
        UpdateEventRequest: {
            /** @enum {string} */
            type?: "lost_found" | "activity" | "club" | "help" | "giveaway" | "happening" | "notice";
            title?: string;
            body?: string;
            location?: components["schemas"]["LatLng"];
            applyable?: boolean;
            /** Format: date-time */
            expiresAt?: string;
            tags?: string[];
        };
        TagItem: {
            name: string;
            slug: string;
            /** Format: int32 */
            usageCount: number;
        };
        TagListResponse: {
            items: components["schemas"]["TagItem"][];
        };
        Limits: {
            /** Format: int32 */
            displayNameMax: number;
            /** Format: int32 */
            passwordMin: number;
            /** Format: int32 */
            passwordMax: number;
            /** Format: int32 */
            titleMin: number;
            /** Format: int32 */
            titleMax: number;
            /** Format: int32 */
            bodyMax: number;
            /** Format: int32 */
            tagsMax: number;
            /** Format: int32 */
            tagNameMin: number;
            /** Format: int32 */
            tagNameMax: number;
            /** Format: int32 */
            messageMax: number;
            /** Format: int32 */
            reportDetailMax: number;
            /** Format: int32 */
            expiryDefaultDays: number;
            /** Format: int32 */
            expiryMaxDays: number;
            /** Format: int32 */
            viewportLimitDefault: number;
            /** Format: int32 */
            viewportLimitMax: number;
        };
        MetaResponse: {
            types: components["schemas"]["TypeMeta"][];
            limits: components["schemas"]["Limits"];
            /** Format: int32 */
            reportThreshold: number;
            googleAuth: boolean;
        };
        TypeMeta: {
            key: string;
            label: string;
            color: string;
            applyableDefault: boolean;
        };
        HealthResponse: {
            status: string;
        };
        EventPin: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "lost_found" | "activity" | "club" | "help" | "giveaway" | "happening" | "notice";
            title: string;
            location: components["schemas"]["LatLng"];
            applyable: boolean;
            /** Format: int32 */
            score: number;
            /** Format: int32 */
            applicationCount: number;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        ViewportResponse: {
            items: components["schemas"]["EventPin"][];
            /** Format: int32 */
            total: number;
            truncated: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query: {
                bbox: string;
                zoom?: number;
                types?: string;
                tags?: string;
                applyable?: boolean;
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ViewportResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    toggle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VoteResponse"];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unhide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TagListResponse"];
                };
            };
        };
    };
    meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
}
