/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["toggle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["renew"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["hide"];
        delete: operations["unhide"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["messages"];
        put?: never;
        post: operations["send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/v1/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateStatus"];
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["myApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MarkReadRequest: {
            ids?: string[];
        };
        CreateEventRequest: {
            /** @enum {string} */
            type: "lost_found" | "activity" | "club" | "help" | "giveaway" | "happening" | "notice";
            title: string;
            body: string;
            location: components["schemas"]["LatLng"];
            applyable: boolean;
            /** Format: date-time */
            expiresAt: string;
            tags: string[];
        };
        LatLng: {
            /** Format: double */
            lng: number;
            /** Format: double */
            lat: number;
        };
        AuthorCard: {
            displayName: string;
            avatarSeed: string;
            /** Format: date-time */
            memberSince: string;
        };
        EventDetail: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "lost_found" | "activity" | "club" | "help" | "giveaway" | "happening" | "notice";
            /** @enum {string} */
            status: "active" | "resolved" | "expired" | "removed" | "under_review";
            title: string;
            body: string;
            location: components["schemas"]["LatLng"];
            applyable: boolean;
            /** Format: int32 */
            score: number;
            /** Format: int32 */
            applicationCount: number;
            tags: components["schemas"]["TagRef"][];
            author: components["schemas"]["AuthorCard"];
            viewerState: components["schemas"]["ViewerState"];
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            resolvedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TagRef: {
            name: string;
            slug: string;
        };
        ViewerState: {
            voted: boolean;
            hidden: boolean;
            applied: boolean;
            isAuthor: boolean;
        };
        VoteResponse: {
            /** Format: int32 */
            score: number;
            voted: boolean;
        };
        ReportRequest: {
            /** @enum {string} */
            reason: "spam" | "offensive" | "scam" | "danger" | "other";
            detail?: string;
        };
        RenewRequest: {
            /** Format: date-time */
            expiresAt: string;
        };
        ApplyRequest: {
            message: string;
        };
        ApplicationResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            eventId: string;
            /** @enum {string} */
            status: "pending" | "accepted" | "declined" | "withdrawn";
            /** Format: date-time */
            createdAt: string;
        };
        ApplyResponse: {
            application: components["schemas"]["ApplicationResponse"];
            /** Format: uuid */
            conversationId: string;
        };
        SendMessageRequest: {
            body: string;
        };
        MessageResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            /** Format: uuid */
            senderId: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            readAt?: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
            displayName: string;
            /** @enum {string} */
            transport?: "cookie" | "bearer";
        };
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
            token?: string;
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            displayName: string;
            avatarSeed: string;
            /** Format: date-time */
            createdAt: string;
        };
        LoginRequest: {
            email: string;
            password: string;
            /** @enum {string} */
            transport?: "cookie" | "bearer";
        };
        UpdateEventRequest: {
            /** @enum {string} */
            type?: "lost_found" | "activity" | "club" | "help" | "giveaway" | "happening" | "notice";
            title?: string;
            body?: string;
            location?: components["schemas"]["LatLng"];
            applyable?: boolean;
            /** Format: date-time */
            expiresAt?: string;
            tags?: string[];
        };
        UpdateApplicationRequest: {
            /** @enum {string} */
            status: "pending" | "accepted" | "declined" | "withdrawn";
        };
        TagItem: {
            name: string;
            slug: string;
            /** Format: int32 */
            usageCount: number;
        };
        TagListResponse: {
            items: components["schemas"]["TagItem"][];
        };
        NotificationListResponse: {
            items: components["schemas"]["NotificationResponse"][];
            /** Format: int32 */
            unreadCount: number;
            nextCursor?: string;
        };
        NotificationResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "application_received" | "application_status" | "message_received" | "event_expiring" | "event_under_review";
            payload: {
                [key: string]: Record<string, never>;
            };
            /** Format: date-time */
            createdAt: string;
        };
        Limits: {
            /** Format: int32 */
            displayNameMax: number;
            /** Format: int32 */
            passwordMin: number;
            /** Format: int32 */
            passwordMax: number;
            /** Format: int32 */
            titleMin: number;
            /** Format: int32 */
            titleMax: number;
            /** Format: int32 */
            bodyMax: number;
            /** Format: int32 */
            tagsMax: number;
            /** Format: int32 */
            tagNameMin: number;
            /** Format: int32 */
            tagNameMax: number;
            /** Format: int32 */
            messageMax: number;
            /** Format: int32 */
            reportDetailMax: number;
            /** Format: int32 */
            expiryDefaultDays: number;
            /** Format: int32 */
            expiryMaxDays: number;
            /** Format: int32 */
            viewportLimitDefault: number;
            /** Format: int32 */
            viewportLimitMax: number;
        };
        MetaResponse: {
            types: components["schemas"]["TypeMeta"][];
            limits: components["schemas"]["Limits"];
            /** Format: int32 */
            reportThreshold: number;
            googleAuth: boolean;
        };
        TypeMeta: {
            key: string;
            label: string;
            color: string;
            applyableDefault: boolean;
        };
        MyEventItem: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "lost_found" | "activity" | "club" | "help" | "giveaway" | "happening" | "notice";
            /** @enum {string} */
            status: "active" | "resolved" | "expired" | "removed" | "under_review";
            title: string;
            location: components["schemas"]["LatLng"];
            applyable: boolean;
            /** Format: int32 */
            score: number;
            /** Format: int32 */
            applicationCount: number;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            resolvedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MyEventsResponse: {
            items: components["schemas"]["MyEventItem"][];
            nextCursor?: string;
        };
        ApplicationGroup: {
            event: components["schemas"]["EventSnippet"];
            applications: components["schemas"]["ApplicationItem"][];
        };
        ApplicationItem: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "pending" | "accepted" | "declined" | "withdrawn";
            message?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            conversationId: string;
            applicant?: components["schemas"]["AuthorCard"];
        };
        EventSnippet: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @enum {string} */
            status: "active" | "resolved" | "expired" | "removed" | "under_review";
        };
        MyApplicationsResponse: {
            items: components["schemas"]["ApplicationGroup"][];
        };
        HealthResponse: {
            status: string;
        };
        ClusterBounds: {
            /** Format: double */
            west: number;
            /** Format: double */
            south: number;
            /** Format: double */
            east: number;
            /** Format: double */
            north: number;
        };
        ClusterPin: {
            /** Format: int32 */
            count: number;
            location: components["schemas"]["LatLng"];
            bounds: components["schemas"]["ClusterBounds"];
        };
        EventPin: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "lost_found" | "activity" | "club" | "help" | "giveaway" | "happening" | "notice";
            title: string;
            location: components["schemas"]["LatLng"];
            applyable: boolean;
            /** Format: int32 */
            score: number;
            /** Format: int32 */
            applicationCount: number;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        ViewportResponse: {
            items: components["schemas"]["EventPin"][];
            clusters: components["schemas"]["ClusterPin"][];
            /** Format: int32 */
            total: number;
        };
        ConversationListResponse: {
            items: components["schemas"]["ConversationSummary"][];
            nextCursor?: string;
        };
        ConversationSummary: {
            /** Format: uuid */
            id: string;
            event: components["schemas"]["EventSnippet"];
            otherParty: components["schemas"]["AuthorCard"];
            /** Format: uuid */
            applicationId: string;
            /** @enum {string} */
            applicationStatus: "pending" | "accepted" | "declined" | "withdrawn";
            /** Format: date-time */
            lastMessageAt: string;
            lastMessageBody?: string;
            /** Format: int32 */
            unreadCount: number;
        };
        MessageListResponse: {
            items: components["schemas"]["MessageResponse"][];
            nextCursor?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    markRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MarkReadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query: {
                bbox: string;
                zoom?: number;
                types?: string;
                tags?: string;
                applyable?: boolean;
                q?: string;
                limit?: number;
                clustered?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ViewportResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    toggle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VoteResponse"];
                };
            };
        };
    };
    resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    renew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    hide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unhide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplyResponse"];
                };
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    messages: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageListResponse"];
                };
            };
        };
    };
    send: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplicationResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApplicationResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TagListResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationListResponse"];
                };
            };
        };
    };
    meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                status?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MyEventsResponse"];
                };
            };
        };
    };
    myApplications: {
        parameters: {
            query: {
                role: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MyApplicationsResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConversationListResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
}
